apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rav5a79bv-python
  janus-idp.io/tekton: rav5a79bv-python
  backstage.io/kubernetes-id: rav5a79bv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rav5a79bv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
